# logging 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

spring:
  profiles:
    active: ["database", "springdoc", "oauth"]
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: 'Asia/Seoul'
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 200MB


# 오류 처리
server:
  error:
    include-exception: true
    include-stacktrace: always
  #port 설정
  port: 8080
