spring:
  h2:
    console:
      enabled: true
      path: /h2-console   # 주소는 http://localhost:8080/h2-console
  datasource:
    url: jdbc:h2:mem:atory;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect