# logging 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

spring:
  profiles:
    active: ["database", "springdoc"]
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: 'Asia/Seoul'

# 오류 처리
server:
  error:
    include-exception: true
    include-stacktrace: always
  #port 설정
  port: 8080

# 데이터베이스 설정 샘플
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atory?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: your-username
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver

# SMS 설정 샘플
sms:
  coolsms:
    api-key: your-coolsms-api-key
    api-secret: your-coolsms-api-secret
    from: your-sender-phone-number

# 공공데이터포털 API 설정 샘플
public:
  data:
    api:
      key: Zy3PSa9cVebmvq0Ca0ljgj6bYl66%2BYSOms%2B5Z22J3yvKDTmDYkNuJjSeyJ6hbZ4EYWfiL8wkQNbb2R8DAbz9hw%3D%3D
      url: https://api.odcloud.kr/api/nts-businessman/v1/status

# Redis 설정 샘플 (선택사항)
spring:
  redis:
    host: localhost
    port: 6379
    password: your-redis-password
    timeout: 2000ms
